//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocxControls.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertiesDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertiesDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocxControls.Resources.PropertiesDescriptions", typeof(PropertiesDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete property.
        /// </summary>
        public static string AlgorithmIdExtensibility {
            get {
                return ResourceManager.GetString("AlgorithmIdExtensibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete property.
        /// </summary>
        public static string AlgorithmIdExtensibilitySource {
            get {
                return ResourceManager.GetString("AlgorithmIdExtensibilitySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the specific cryptographic hashing algorithm which shall be used along with the salt attribute and input password in order to compute the hash value..
        /// </summary>
        public static string AlgorithmName {
            get {
                return ResourceManager.GetString("AlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the name of the application that created this document..
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the version of the application which produced this document.&lt;p/&gt;The content of this element shall be of the form XX.YYYY where X and Y represent numerical values, or the document shall be considered non-conformant.&lt;p/&gt;Note: The contents of this element do not represent absolute values, but rather qualify the contents of the Application element to differentiate between different versions of the same producer. Applications should use this information in an informative manner only (as document metada [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the category of the content that is contained in the document..
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the total number of characters in a document..
        /// </summary>
        public static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the last count of the number of characters (including spaces) in this document..
        /// </summary>
        public static string CharactersWithSpaces {
            get {
                return ResourceManager.GetString("CharactersWithSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the name of a company associated with the document..
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example values include &quot;Draft&quot;, &quot;Reviewed&quot;, and &quot;Final&quot;..
        /// </summary>
        public static string ContentStatus {
            get {
                return ResourceManager.GetString("ContentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example values include &quot;Whitepaper&quot;, &quot;Security Bulletin&quot;, and &quot;Exam&quot;.&lt;p/&gt;This property is distinct from Multipurpose Internet Mail Extensions (MIME) content types as defined in RFC 2616..
        /// </summary>
        public static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically set by application..
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically set by application..
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete property.
        /// </summary>
        public static string CryptographicAlgorithmClass {
            get {
                return ResourceManager.GetString("CryptographicAlgorithmClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete property.
        /// </summary>
        public static string CryptographicAlgorithmSid {
            get {
                return ResourceManager.GetString("CryptographicAlgorithmSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete property.
        /// </summary>
        public static string CryptographicAlgorithmType {
            get {
                return ResourceManager.GetString("CryptographicAlgorithmType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete property.
        /// </summary>
        public static string CryptographicProvider {
            get {
                return ResourceManager.GetString("CryptographicProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete property.
        /// </summary>
        public static string CryptographicProviderType {
            get {
                return ResourceManager.GetString("CryptographicProviderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete property.
        /// </summary>
        public static string CryptographicProviderTypeExtensibility {
            get {
                return ResourceManager.GetString("CryptographicProviderTypeExtensibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete property.
        /// </summary>
        public static string CryptographicProviderTypeExtSource {
            get {
                return ResourceManager.GetString("CryptographicProviderTypeExtSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete property.
        /// </summary>
        public static string CryptographicSpinCount {
            get {
                return ResourceManager.GetString("CryptographicSpinCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description may include but is not limited to: an abstract, table of contents, reference to a graphical representation of content, or a free-text account of the content..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains the signature of a digitally signed document.&lt;p/&gt;Note: This property is a mechanism used by legacy documents to store the digital signature of its binary representation, and should be avoided in favor of the well-defined mechanism defined in Part 2. Any use of this property should be for legacy compatibility only, and is application-defined..
        /// </summary>
        public static string DigitalSignature {
            get {
                return ResourceManager.GetString("DigitalSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the security level of a document as a numeric value. Document security is defined as follows:&lt;br/&gt;1 - Document is password protected.&lt;br/&gt;2 - Document is recommended to be opened as read-only.&lt;br/&gt;4 - Document is enforced to be opened as read-only.&lt;br/&gt;8 - Document is locked for annotation..
        /// </summary>
        public static string DocumentSecurity {
            get {
                return ResourceManager.GetString("DocumentSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the set of editing restrictions which shall be enforced on a given WordprocessingML document..
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if the document protection RunProperties shall be enforced for a given WordprocessingML document. If the value of this element is off, 0, or false, all the WordprocessingML pertaining to document protection is still preserved in the document, but is not enforced. If the value of this element is on, 1, or true, the document protection is enforced..
        /// </summary>
        public static string Enforcement {
            get {
                return ResourceManager.GetString("Enforcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if formatting restrictions are in effect for a given WordprocessingML document. This enables the document to restrict the types of styles that can exist in a given WordprocessingML document. Specifically, by setting this attribute&apos;s value equal to true, every style whose locked element (§17.7.4.7) has a value of true (or latent styles (§17.7.4.5) whose locked attribute is true) shall not be available for use in the application, nor should any direct formatting. Only styles with a locked value of f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Formatting {
            get {
                return ResourceManager.GetString("Formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete property.
        /// </summary>
        public static string Hash {
            get {
                return ResourceManager.GetString("Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the hash value for the password stored with this document. This value shall be compared with the resulting hash value after hashing the user-supplied password using the algorithm specified by the preceding attributes and owner XML element, and if the two values match, the protection shall no longer be enforced..
        /// </summary>
        public static string HashValue {
            get {
                return ResourceManager.GetString("HashValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading pairs indicates the grouping of document parts and the number of parts in each group. These parts are not document parts but conceptual representations of document sections..
        /// </summary>
        public static string HeadingPairs {
            get {
                return ResourceManager.GetString("HeadingPairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the base string used for evaluating relative hyperlinks in this document..
        /// </summary>
        public static string HyperlinkBase {
            get {
                return ResourceManager.GetString("HyperlinkBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the set of hyperlinks that were in this document when last saved..
        /// </summary>
        public static string HyperlinkList {
            get {
                return ResourceManager.GetString("HyperlinkList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies that one or more hyperlinks in this part were updated exclusively in this part by a producer. The next producer to open this document shall update the hyperlink relationships with the new hyperlinks specified in this part..
        /// </summary>
        public static string HyperlinksChanged {
            get {
                return ResourceManager.GetString("HyperlinksChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A string that identifies this document.
        /// </summary>
        public static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A delimited set of keywords to support searching and indexing the document and content.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language of the document content.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically set by application..
        /// </summary>
        public static string LastModifiedBy {
            get {
                return ResourceManager.GetString("LastModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically set by application..
        /// </summary>
        public static string LastPrinted {
            get {
                return ResourceManager.GetString("LastPrinted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the total number of lines in a document when last saved by a conforming producer if applicable..
        /// </summary>
        public static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether hyperlinks in a document are up-to-date. Set this element to TRUE to indicate that hyperlinks are updated. Set this element to FALSE to indicate that hyperlinks are outdated..
        /// </summary>
        public static string LinksUpToDate {
            get {
                return ResourceManager.GetString("LinksUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the name of a supervisor associated with the document..
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically set by application..
        /// </summary>
        public static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of multimedia clips contained in the document.
        /// </summary>
        public static string MultimediaClips {
            get {
                return ResourceManager.GetString("MultimediaClips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the total number of pages of a document if applicable..
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the total number of paragraphs found in a document if applicable..
        /// </summary>
        public static string Paragraphs {
            get {
                return ResourceManager.GetString("Paragraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the intended format for a presentation document. For example, a presentation intended to be shown on video has PresentationFormat &quot;Video&quot;..
        /// </summary>
        public static string PresentationFormat {
            get {
                return ResourceManager.GetString("PresentationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the number of changed saves or revisions.&lt;p/&gt;The application is responsible for updating the Revision property value after each revision..
        /// </summary>
        public static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete property.
        /// </summary>
        public static string Salt {
            get {
                return ResourceManager.GetString("Salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the salt which was prepended to the user-supplied password before it was hashed using the hashing algorithm defined by the preceding attribute values to generate the hashValue attribute, and which shall also be prepended to the user-supplied password before attempting to generate a hash value for comparison. A salt is a random string which is added to a user-supplied password before it is hashed in order to prevent a malicious party from pre-calculating all possible password/hash combinations and  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SaltValue {
            get {
                return ResourceManager.GetString("SaltValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the display mode of the document thumbnail. Set this element to TRUE to enable scaling of the document thumbnail to the display. Set this element to FALSE to enable cropping of the document thumbnail to show only sections that fits the display..
        /// </summary>
        public static string ScaleCrop {
            get {
                return ResourceManager.GetString("ScaleCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if this document is currently shared between multiple producers. If this element is set to TRUE, producers should take care when updating the document..
        /// </summary>
        public static string SharedDocument {
            get {
                return ResourceManager.GetString("SharedDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the number of times the hashing function shall be iteratively run (runs using each iteration&apos;s result plus a 4 byte value (0-based, little endian) containing the number of the iteration as the input for the next iteration) when attempting to compare a user-supplied
        ///password with the value stored in the hashValue attribute..
        /// </summary>
        public static string SpinCount {
            get {
                return ResourceManager.GetString("SpinCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A string that identifies the topic of this document.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the name of an external document template containing format and style information used to create the current document..
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A string that is presented as the title of this document.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the title of each document. These parts are not document parts but conceptual representations of document sections..
        /// </summary>
        public static string TitlesOfParts {
            get {
                return ResourceManager.GetString("TitlesOfParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total time that a document has been edited. The default time unit is minutes..
        /// </summary>
        public static string TotalTime {
            get {
                return ResourceManager.GetString("TotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A string that identifies the version of this document.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the total number of words contained in a document when last saved..
        /// </summary>
        public static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
    }
}
