//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocxControls.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertiesTooltips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertiesTooltips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocxControls.Resources.PropertiesTooltips", typeof(PropertiesTooltips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptographic Algorithm Extensibility.
        /// </summary>
        public static string AlgorithmIdExtensibility {
            get {
                return ResourceManager.GetString("AlgorithmIdExtensibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm Extensibility Source.
        /// </summary>
        public static string AlgorithmIdExtensibilitySource {
            get {
                return ResourceManager.GetString("AlgorithmIdExtensibilitySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptographic Algorithm Name.
        /// </summary>
        public static string AlgorithmName {
            get {
                return ResourceManager.GetString("AlgorithmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application name.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application version.
        /// </summary>
        public static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category of the document.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of characters.
        /// </summary>
        public static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of characters.
        /// </summary>
        public static string CharactersWithSpaces {
            get {
                return ResourceManager.GetString("CharactersWithSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status of the document content.
        /// </summary>
        public static string ContentStatus {
            get {
                return ResourceManager.GetString("ContentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of content that is contained in the document.
        /// </summary>
        public static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date and time the document was initially created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The individual or entity that created the document and its content.
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptographic Algorithm Class.
        /// </summary>
        public static string CryptographicAlgorithmClass {
            get {
                return ResourceManager.GetString("CryptographicAlgorithmClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptographic Hashing Algorithm.
        /// </summary>
        public static string CryptographicAlgorithmSid {
            get {
                return ResourceManager.GetString("CryptographicAlgorithmSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptographic Algorithm Type.
        /// </summary>
        public static string CryptographicAlgorithmType {
            get {
                return ResourceManager.GetString("CryptographicAlgorithmType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptographic Provider.
        /// </summary>
        public static string CryptographicProvider {
            get {
                return ResourceManager.GetString("CryptographicProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptographic Provider Type.
        /// </summary>
        public static string CryptographicProviderType {
            get {
                return ResourceManager.GetString("CryptographicProviderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptographic Provider Type Extensibility.
        /// </summary>
        public static string CryptographicProviderTypeExtensibility {
            get {
                return ResourceManager.GetString("CryptographicProviderTypeExtensibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Type Extensibility Source.
        /// </summary>
        public static string CryptographicProviderTypeExtSource {
            get {
                return ResourceManager.GetString("CryptographicProviderTypeExtSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterations to Run Hashing Algorithm.
        /// </summary>
        public static string CryptographicSpinCount {
            get {
                return ResourceManager.GetString("CryptographicSpinCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A description of the content contained in the document.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital signature.
        /// </summary>
        public static string DigitalSignature {
            get {
                return ResourceManager.GetString("DigitalSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document security.
        /// </summary>
        public static string DocumentSecurity {
            get {
                return ResourceManager.GetString("DocumentSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Editing Restrictions.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforce Document Protection RunProperties.
        /// </summary>
        public static string Enforcement {
            get {
                return ResourceManager.GetString("Enforcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Allow Formatting With Unlocked Styles.
        /// </summary>
        public static string Formatting {
            get {
                return ResourceManager.GetString("Formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Hash.
        /// </summary>
        public static string Hash {
            get {
                return ResourceManager.GetString("Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash value.
        /// </summary>
        public static string HashValue {
            get {
                return ResourceManager.GetString("HashValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading pairs.
        /// </summary>
        public static string HeadingPairs {
            get {
                return ResourceManager.GetString("HeadingPairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative hyperlink base.
        /// </summary>
        public static string HyperlinkBase {
            get {
                return ResourceManager.GetString("HyperlinkBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperlink list.
        /// </summary>
        public static string HyperlinkList {
            get {
                return ResourceManager.GetString("HyperlinkList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperlinks changed.
        /// </summary>
        public static string HyperlinksChanged {
            get {
                return ResourceManager.GetString("HyperlinksChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document identifier.
        /// </summary>
        public static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document keywords.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value that identifies the document content language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user who last modified the document content.
        /// </summary>
        public static string LastModifiedBy {
            get {
                return ResourceManager.GetString("LastModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date and time the document content was last printed.
        /// </summary>
        public static string LastPrinted {
            get {
                return ResourceManager.GetString("LastPrinted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of lines.
        /// </summary>
        public static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links up-to-date.
        /// </summary>
        public static string LinksUpToDate {
            get {
                return ResourceManager.GetString("LinksUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is locked for annotation.
        /// </summary>
        public static string LockedForAnnotation {
            get {
                return ResourceManager.GetString("LockedForAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of manager.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date and time the document was last changed.
        /// </summary>
        public static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of multimedia clips.
        /// </summary>
        public static string MultimediaClips {
            get {
                return ResourceManager.GetString("MultimediaClips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of page.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of paragraphs.
        /// </summary>
        public static string Paragraphs {
            get {
                return ResourceManager.GetString("Paragraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is password protected.
        /// </summary>
        public static string PasswordProtected {
            get {
                return ResourceManager.GetString("PasswordProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intended format of presentation.
        /// </summary>
        public static string PresentationFormat {
            get {
                return ResourceManager.GetString("PresentationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is recommended to be opened as read-only.
        /// </summary>
        public static string ReadOnlyForced {
            get {
                return ResourceManager.GetString("ReadOnlyForced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is recommended to be opened as read-only.
        /// </summary>
        public static string ReadOnlyRecommended {
            get {
                return ResourceManager.GetString("ReadOnlyRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The revision number of the document.
        /// </summary>
        public static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salt for Password Verifier.
        /// </summary>
        public static string Salt {
            get {
                return ResourceManager.GetString("Salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salt value.
        /// </summary>
        public static string SaltValue {
            get {
                return ResourceManager.GetString("SaltValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail display mode.
        /// </summary>
        public static string ScaleCrop {
            get {
                return ResourceManager.GetString("ScaleCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared document.
        /// </summary>
        public static string SharedDocument {
            get {
                return ResourceManager.GetString("SharedDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin count.
        /// </summary>
        public static string SpinCount {
            get {
                return ResourceManager.GetString("SpinCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The topic of the document content.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of document template.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name given to the document and its content.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part titles.
        /// </summary>
        public static string TitlesOfParts {
            get {
                return ResourceManager.GetString("TitlesOfParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total edit time.
        /// </summary>
        public static string TotalTime {
            get {
                return ResourceManager.GetString("TotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version number of the document.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word count.
        /// </summary>
        public static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
    }
}
