//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocxControls.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsTooltips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsTooltips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocxControls.Resources.SettingsTooltips", typeof(SettingsTooltips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grammar checking settings.
        /// </summary>
        public static string ActiveWritingStyle {
            get {
                return ResourceManager.GetString("ActiveWritingStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align paragraph and table borders with page border.
        /// </summary>
        public static string AlignBorderAndEdges {
            get {
                return ResourceManager.GetString("AlignBorderAndEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not mark custom XML elements with no namespace as invalid.
        /// </summary>
        public static string AlwaysMergeEmptyNamespace {
            get {
                return ResourceManager.GetString("AlwaysMergeEmptyNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom XML element names as default placeholder text.
        /// </summary>
        public static string AlwaysShowPlaceholderText {
            get {
                return ResourceManager.GetString("AlwaysShowPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached custom XML schema.
        /// </summary>
        public static string AttachedSchema {
            get {
                return ResourceManager.GetString("AttachedSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached document template.
        /// </summary>
        public static string AttachedTemplate {
            get {
                return ResourceManager.GetString("AttachedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow automatic formatting to override formatting protection settings.
        /// </summary>
        public static string AutoFormatOverride {
            get {
                return ResourceManager.GetString("AutoFormatOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically hyphenate document contents when displayed.
        /// </summary>
        public static string AutoHyphenation {
            get {
                return ResourceManager.GetString("AutoHyphenation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book fold printing.
        /// </summary>
        public static string BookFoldPrinting {
            get {
                return ResourceManager.GetString("BookFoldPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of pages per booklet.
        /// </summary>
        public static string BookFoldPrintingSheets {
            get {
                return ResourceManager.GetString("BookFoldPrintingSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse book fold printing.
        /// </summary>
        public static string BookFoldReversePrinting {
            get {
                return ResourceManager.GetString("BookFoldReversePrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page border excludes footer.
        /// </summary>
        public static string BordersDoNotSurroundFooter {
            get {
                return ResourceManager.GetString("BordersDoNotSurroundFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page border excludes header.
        /// </summary>
        public static string BordersDoNotSurroundHeader {
            get {
                return ResourceManager.GetString("BordersDoNotSurroundHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption settings.
        /// </summary>
        public static string Captions {
            get {
                return ResourceManager.GetString("Captions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character-level whitespace compression.
        /// </summary>
        public static string CharacterSpacingControl {
            get {
                return ResourceManager.GetString("CharacterSpacingControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datapoint properties and datalabels behavior.
        /// </summary>
        public static string ChartTrackingRefBased {
            get {
                return ResourceManager.GetString("ChartTrackingRefBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph style applied to automatically generated paragraphs.
        /// </summary>
        public static string ClickAndTypeStyle {
            get {
                return ResourceManager.GetString("ClickAndTypeStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme color mappings.
        /// </summary>
        public static string ColorSchemeMapping {
            get {
                return ResourceManager.GetString("ColorSchemeMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility settings.
        /// </summary>
        public static string Compatibility {
            get {
                return ResourceManager.GetString("Compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was resolving conflicting edits when the document was saved.
        /// </summary>
        public static string ConflictMode {
            get {
                return ResourceManager.GetString("ConflictMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of consecutively hyphenated lines.
        /// </summary>
        public static string ConsecutiveHyphenLimit {
            get {
                return ResourceManager.GetString("ConsecutiveHyphenLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radix point for field code evaluation.
        /// </summary>
        public static string DecimalSymbol {
            get {
                return ResourceManager.GetString("DecimalSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution in dots per inch (DPI) at which images in the document will be saved.
        /// </summary>
        public static string DefaultImageDpi {
            get {
                return ResourceManager.GetString("DefaultImageDpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default table style for newly inserted tables.
        /// </summary>
        public static string DefaultTableStyle {
            get {
                return ResourceManager.GetString("DefaultTableStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance between automatic tab stops.
        /// </summary>
        public static string DefaultTabStop {
            get {
                return ResourceManager.GetString("DefaultTabStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cropped-out areas of the images are not to be saved.
        /// </summary>
        public static string DiscardImageEditingData {
            get {
                return ResourceManager.GetString("DiscardImageEditingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display background objects when displaying document.
        /// </summary>
        public static string DisplayBackgroundShape {
            get {
                return ResourceManager.GetString("DisplayBackgroundShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance between horizontal gridlines.
        /// </summary>
        public static string DisplayHorizontalDrawingGrid {
            get {
                return ResourceManager.GetString("DisplayHorizontalDrawingGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance between vertical gridlines.
        /// </summary>
        public static string DisplayVerticalDrawingGrid {
            get {
                return ResourceManager.GetString("DisplayVerticalDrawingGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbitrary identifier for the context of the paragraph identifiers in the document.
        /// </summary>
        public static string DocumentId {
            get {
                return ResourceManager.GetString("DocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document editing restrictions.
        /// </summary>
        public static string DocumentProtection {
            get {
                return ResourceManager.GetString("DocumentProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document classification.
        /// </summary>
        public static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document variables.
        /// </summary>
        public static string DocumentVariables {
            get {
                return ResourceManager.GetString("DocumentVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not automatically compress images.
        /// </summary>
        public static string DoNotAutoCompressPictures {
            get {
                return ResourceManager.GetString("DoNotAutoCompressPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show visual indicator for invalid custom XML markup.
        /// </summary>
        public static string DoNotDemarcateInvalidXml {
            get {
                return ResourceManager.GetString("DoNotDemarcateInvalidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not display visual boundary for header/footer or between pages.
        /// </summary>
        public static string DoNotDisplayPageBoundaries {
            get {
                return ResourceManager.GetString("DoNotDisplayPageBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not hyphenate words in all capital letters.
        /// </summary>
        public static string DoNotHyphenateCaps {
            get {
                return ResourceManager.GetString("DoNotHyphenateCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not include content in text boxes, footnotes, and endnotes in document statistics.
        /// </summary>
        public static string DoNotIncludeSubdocsInStats {
            get {
                return ResourceManager.GetString("DoNotIncludeSubdocsInStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show visual indicator for form fields.
        /// </summary>
        public static string DoNotShadeFormData {
            get {
                return ResourceManager.GetString("DoNotShadeFormData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not track formatting revisions when tracking revisions.
        /// </summary>
        public static string DoNotTrackFormatting {
            get {
                return ResourceManager.GetString("DoNotTrackFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use move syntax when tracking revisions.
        /// </summary>
        public static string DoNotTrackMoves {
            get {
                return ResourceManager.GetString("DoNotTrackMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use margins for drawing grid origin.
        /// </summary>
        public static string DoNotUseMarginsForDrawingGridOrigin {
            get {
                return ResourceManager.GetString("DoNotUseMarginsForDrawingGridOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not validate custom XML markup against schemas.
        /// </summary>
        public static string DoNotValidateAgainstSchema {
            get {
                return ResourceManager.GetString("DoNotValidateAgainstSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing grid horizontal origin point.
        /// </summary>
        public static string DrawingGridHorizontalOrigin {
            get {
                return ResourceManager.GetString("DrawingGridHorizontalOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing grid horizontal grid unit size.
        /// </summary>
        public static string DrawingGridHorizontalSpacing {
            get {
                return ResourceManager.GetString("DrawingGridHorizontalSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing grid vertical origin point.
        /// </summary>
        public static string DrawingGridVerticalOrigin {
            get {
                return ResourceManager.GetString("DrawingGridVerticalOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing grid vertical grid unit size.
        /// </summary>
        public static string DrawingGridVerticalSpacing {
            get {
                return ResourceManager.GetString("DrawingGridVerticalSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed common system fonts.
        /// </summary>
        public static string EmbedSystemFonts {
            get {
                return ResourceManager.GetString("EmbedSystemFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed truetype fonts.
        /// </summary>
        public static string EmbedTrueTypeFonts {
            get {
                return ResourceManager.GetString("EmbedTrueTypeFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document-wide endnote properties.
        /// </summary>
        public static string EndnoteDocumentWideProperties {
            get {
                return ResourceManager.GetString("EndnoteDocumentWideProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different even/odd page headers and footers.
        /// </summary>
        public static string EvenAndOddHeaders {
            get {
                return ResourceManager.GetString("EvenAndOddHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document-wide footnote properties.
        /// </summary>
        public static string FootnoteDocumentWideProperties {
            get {
                return ResourceManager.GetString("FootnoteDocumentWideProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade document on open.
        /// </summary>
        public static string ForceUpgrade {
            get {
                return ResourceManager.GetString("ForceUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured document tag placeholder text should be resaved.
        /// </summary>
        public static string FormsDesign {
            get {
                return ResourceManager.GetString("FormsDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position gutter at top of page.
        /// </summary>
        public static string GutterAtTop {
            get {
                return ResourceManager.GetString("GutterAtTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default parameters for object using the VML syntax inserted in the header and footer.
        /// </summary>
        public static string HeaderShapeDefaults {
            get {
                return ResourceManager.GetString("HeaderShapeDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not display visual indication of grammatical errors.
        /// </summary>
        public static string HideGrammaticalErrors {
            get {
                return ResourceManager.GetString("HideGrammaticalErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not display visual indication of spelling errors.
        /// </summary>
        public static string HideSpellingErrors {
            get {
                return ResourceManager.GetString("HideSpellingErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyphenation zone.
        /// </summary>
        public static string HyphenationZone {
            get {
                return ResourceManager.GetString("HyphenationZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore mixed content when validating custom XML markup.
        /// </summary>
        public static string IgnoreMixedContent {
            get {
                return ResourceManager.GetString("IgnoreMixedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically update styles from document template.
        /// </summary>
        public static string LinkStyles {
            get {
                return ResourceManager.GetString("LinkStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List separator for field code evaluation.
        /// </summary>
        public static string ListSeparator {
            get {
                return ResourceManager.GetString("ListSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail merge settings.
        /// </summary>
        public static string MailMerge {
            get {
                return ResourceManager.GetString("MailMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math properties.
        /// </summary>
        public static string MathProperties {
            get {
                return ResourceManager.GetString("MathProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror page margins.
        /// </summary>
        public static string MirrorMargins {
            get {
                return ResourceManager.GetString("MirrorMargins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom set of characters which cannot end a line.
        /// </summary>
        public static string NoLineBreaksAfterKinsoku {
            get {
                return ResourceManager.GetString("NoLineBreaksAfterKinsoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom set of characters which cannot begin a line.
        /// </summary>
        public static string NoLineBreaksBeforeKinsoku {
            get {
                return ResourceManager.GetString("NoLineBreaksBeforeKinsoku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never kern punctuation characters.
        /// </summary>
        public static string NoPunctuationKerning {
            get {
                return ResourceManager.GetString("NoPunctuationKerning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique identifier for a set of documents derived from a common source.
        /// </summary>
        public static string PersistentDocumentId {
            get {
                return ResourceManager.GetString("PersistentDocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only print form field content.
        /// </summary>
        public static string PrintFormsData {
            get {
                return ResourceManager.GetString("PrintFormsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print fractional character widths.
        /// </summary>
        public static string PrintFractionalCharacterWidth {
            get {
                return ResourceManager.GetString("PrintFractionalCharacterWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print postscript codes with document text.
        /// </summary>
        public static string PrintPostScriptOverText {
            get {
                return ResourceManager.GetString("PrintPostScriptOverText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print two pages per sheet.
        /// </summary>
        public static string PrintTwoOnOne {
            get {
                return ResourceManager.GetString("PrintTwoOnOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spelling and grammatical checking state.
        /// </summary>
        public static string ProofState {
            get {
                return ResourceManager.GetString("ProofState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze document layout.
        /// </summary>
        public static string ReadModeInkLockDown {
            get {
                return ResourceManager.GetString("ReadModeInkLockDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove date and time from annotations.
        /// </summary>
        public static string RemoveDateAndTime {
            get {
                return ResourceManager.GetString("RemoveDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove personal information from document properties.
        /// </summary>
        public static string RemovePersonalInformation {
            get {
                return ResourceManager.GetString("RemovePersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility of annotation types.
        /// </summary>
        public static string RevisionView {
            get {
                return ResourceManager.GetString("RevisionView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing of all revision save id values.
        /// </summary>
        public static string Rsids {
            get {
                return ResourceManager.GetString("Rsids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only save form field content.
        /// </summary>
        public static string SaveFormsData {
            get {
                return ResourceManager.GetString("SaveFormsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow saving document as XML file when custom XML markup is invalid.
        /// </summary>
        public static string SaveInvalidXml {
            get {
                return ResourceManager.GetString("SaveInvalidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate thumbnail for document on save.
        /// </summary>
        public static string SavePreviewPicture {
            get {
                return ResourceManager.GetString("SavePreviewPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subset fonts when embedding.
        /// </summary>
        public static string SaveSubsetFonts {
            get {
                return ResourceManager.GetString("SaveSubsetFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom XSL transform to use when saving as XML file.
        /// </summary>
        public static string SaveThroughXslt {
            get {
                return ResourceManager.GetString("SaveThroughXslt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only save custom XML markup.
        /// </summary>
        public static string SaveXmlDataOnly {
            get {
                return ResourceManager.GetString("SaveXmlDataOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedded custom XML schema supplementary data.
        /// </summary>
        public static string SchemaLibrary {
            get {
                return ResourceManager.GetString("SchemaLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default parameters for object using the VML syntax inserted in the body.
        /// </summary>
        public static string ShapeDefaults {
            get {
                return ResourceManager.GetString("ShapeDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show e-mail message header.
        /// </summary>
        public static string ShowEnvelope {
            get {
                return ResourceManager.GetString("ShowEnvelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show visual indicators for custom XML markup start/end locations.
        /// </summary>
        public static string ShowXmlTags {
            get {
                return ResourceManager.GetString("ShowXmlTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use strict kinsoku rules for japanese text.
        /// </summary>
        public static string StrictFirstAndLastChars {
            get {
                return ResourceManager.GetString("StrictFirstAndLastChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent replacement of styles part.
        /// </summary>
        public static string StyleLockStylesPart {
            get {
                return ResourceManager.GetString("StyleLockStylesPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent modification of themes part.
        /// </summary>
        public static string StyleLockThemesPart {
            get {
                return ResourceManager.GetString("StyleLockThemesPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested filtering for list of document styles.
        /// </summary>
        public static string StylePaneFormatFilter {
            get {
                return ResourceManager.GetString("StylePaneFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested sorting for list of document styles.
        /// </summary>
        public static string StylePaneSortMethods {
            get {
                return ResourceManager.GetString("StylePaneSortMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of document to use when generating summary.
        /// </summary>
        public static string SummaryLength {
            get {
                return ResourceManager.GetString("SummaryLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme font languages.
        /// </summary>
        public static string ThemeFontLanguages {
            get {
                return ResourceManager.GetString("ThemeFontLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track revisions to document.
        /// </summary>
        public static string TrackRevisions {
            get {
                return ResourceManager.GetString("TrackRevisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User interface compatible with old Word versions.
        /// </summary>
        public static string UICompatibleWith97To2003 {
            get {
                return ResourceManager.GetString("UICompatibleWith97To2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically recalculate fields on open.
        /// </summary>
        public static string UpdateFieldsOnOpen {
            get {
                return ResourceManager.GetString("UpdateFieldsOnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save document as XML file through custom XSL transform.
        /// </summary>
        public static string UseXsltWhenSaving {
            get {
                return ResourceManager.GetString("UseXsltWhenSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document view setting.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write protection.
        /// </summary>
        public static string WriteProtection {
            get {
                return ResourceManager.GetString("WriteProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnification setting.
        /// </summary>
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
